### ISSUE TITLE
can transfiner used for Semantic Segmentation?

### ISSUE THREAD

**Issue by zhangyunming** [SysCV/transfiner#12]
hi, it really a nice work , and  can transfiner used for Semantic Segmentation?

**Comment by lkeab** [comment]
Yes, if you would like to optimize the semantic segmentation details and accuracy. One quick thought is to replace instance to each class.

**Comment by cenchaojun** [comment]
> hi, it really a nice work , and can transfiner used for Semantic Segmentation?

it really a nice work, but I still can't find the code area corresponding to the module😂
