### ISSUE TITLE
How do I train on my own customized coco dataset?

### ISSUE THREAD

**Issue by YellowPuppy** [SysCV/transfiner#13]
How do I train on my own customized coco dataset?
![issue](https://user-images.githubusercontent.com/94440332/164079177-0e40b54f-52f7-484d-9409-7d847712996c.png)

**Comment by lkeab** [comment]
Hi, you could refer to the instructions [here](https://towardsdatascience.com/train-maskrcnn-on-custom-dataset-with-detectron2-in-4-steps-5887a6aa135d) or [here](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#use-custom-datasets).

**Comment by INF800** [comment]
[train_4gpu_transfiner_3x.sh](https://github.com/SysCV/transfiner/blob/main/scripts/train_4gpu_transfiner_3x.sh)
[train_4gpu_transfiner_3x_101.sh](https://github.com/SysCV/transfiner/blob/main/scripts/train_4gpu_transfiner_3x_101.sh)
[train_4gpu_transfiner_3x_101_deform.sh](https://github.com/SysCV/transfiner/blob/main/scripts/train_4gpu_transfiner_3x_101_deform.sh)
[train_4gpu_transfiner_3x_deform.sh](https://github.com/SysCV/transfiner/blob/main/scripts/train_4gpu_transfiner_3x_deform.sh)


In the above scripts what does `deform` mean?

**Comment by lkeab** [comment]
training with the DCN module

**Comment by INF800** [comment]
> "deform" means training with the DCN module

How does it affect the accuracy? IoU of boundaries to be specific.

**Comment by lkeab** [comment]
usually bring improvement about 1.5  point in boundary ap.

**Comment by INF800** [comment]
Can we use this repo for both instance segmentation and semantic segmentation?

Or is it only restricted to one of the above tasks currently?

**Comment by lkeab** [comment]
This is panoptic segmentation. You could adapt our method to this task. I think there are also some works using detectron2 for panoptic segmentation.

**Comment by INF800** [comment]
Apologies for confusion. I meant - can I use this (instance segmentation) project for semantic segmentation with high accuracy for edges?

**Comment by INF800** [comment]
> Apologies for confusion. I meant - can I use this (instance segmentation) project for semantic segmentation with high accuracy for edges?

If yes, what changes must I make to codebase. I am well versed with Detectron2

**Comment by lkeab** [comment]
I am not that familiar with it. But I think you can refer to [this](https://github.com/facebookresearch/detectron2/issues/1055).

**Comment by INF800** [comment]
Does model support semantic segmentation task.

In instance segmentation we have a bbox regression and output masks for every bbox.

But in semantic segmentation we only have output masks

**Comment by lkeab** [comment]
you could treat the whole image as the largest bounding box.
