### ISSUE TITLE
PyTorch CUDA out of memory

### ISSUE THREAD

**Issue by 616099859** [SysCV/transfiner#14]
RuntimeError: CUDA out of memory

**Comment by 616099859** [comment]
Great project, I want to know that my computer has only 2G video memory, when I run code CUDA out of memory appears, but, DETECtron2 project I run completely no problem, how to limit GPU? thank you！

**Comment by lkeab** [comment]
for the very small 2G video memory, one quickest trial is to resize the image to a small scale; reducing batch size to 1; or using a lightweight backbone (r50).
