### ISSUE TITLE
ImportError: cannot import name '_C' from 'detectron2'

### ISSUE THREAD

**Issue by 906070493** [SysCV/transfiner#15]
ImportError: cannot import name '_C' from 'detectron2'怎么破啊

**Comment by lkeab** [comment]
have you tried this command "python3 setup.py build develop"?

**Comment by 906070493** [comment]
试过，没反应，然后我去官网下个detectron2把这个覆盖就不报错了

**Comment by 906070493** [comment]
试了，没有反应，然后我去官网下个detectron2把覆盖就不报错了

**Comment by 906070493** [comment]
测试的话是运行那个demo就可以吗,我是在windows安装的

**Comment by lkeab** [comment]
you could use this [script](https://github.com/SysCV/transfiner#visualization)

**Comment by 906070493** [comment]
i have solved this problem, but i meet a new problem, how to run this program with gpu, it said that it doesn't find the ROIAlign_gpu.obj, i find that there is only ROIAlign_cpu.obj

**Comment by lkeab** [comment]
the code uses the gpu by default, I guess it may be related to your windows installation version of detectron2.

**Comment by 906070493** [comment]
thank you for your patience, should i run the demo.py?

**Comment by lkeab** [comment]
we provided the instructions [here](https://github.com/SysCV/transfiner#visualization)
