### ISSUE TITLE
No predictions from the model!

### ISSUE THREAD

**Issue by Fhujinwu** [SysCV/transfiner#17]
When I was testing COCO2017, the following error occurred：

[04/02 16:19:28 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[04/02 16:19:28 d2.evaluation.coco_evaluation]: Saving results to ./output/inference/coco_instances_results.json
[04/02 16:19:28 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
/home/Bxl/hujinwu/experience/transfiner-main/detectron2/evaluation/coco_evaluation.py:329: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  self._logger.warn("No predictions from the model!")
WARNING [04/02 16:19:28 d2.evaluation.coco_evaluation]: No predictions from the model!
[04/02 16:19:28 d2.engine.defaults]: Evaluation results for coco_2017_val in csv format:
[04/02 16:19:28 d2.evaluation.testing]: copypaste: Task: bbox
[04/02 16:19:28 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[04/02 16:19:28 d2.evaluation.testing]: copypaste: nan,nan,nan,nan,nan,nan

Hello. Please tell me why there are "**No predictions from the model!“** thanks.

**Comment by lkeab** [comment]
which command leads to this error? is the validation annotation file in the correct place?

**Comment by Fhujinwu** [comment]
1. The command I use is :
 python tools/train_net.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x_4gpu_transfiner.yaml --num-gpus 1 --eval-only MODEL.WEIGHTS xxxxx/transfiner-main/output/model_final.pth
2.Verification set location is correct.

I look forward to your suggestions.

**Comment by lkeab** [comment]
what is your used model_final.pth? does it match the setting of the config file, such as both r50?

**Comment by Fhujinwu** [comment]
Hi, model_final.pth is the result of my trained model. I tried the training model you provided and I also get the error above. The environment I am using is python 3.6 + torch1.6.0 + cu92 + torchvision0.7.0 + cu92.
I look forward to your suggestions. thanks. could this be the cause of the error?

**Comment by lkeab** [comment]
what about the config file matching question? is the loss decreasing normally in your training log?

**Comment by Fhujinwu** [comment]
Thank you for your help. When I changed the environment to "torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=9.2", it solved the problem.
