### ISSUE TITLE
Some model parameters or buffers are not found in the checkpoint

### ISSUE THREAD

**Issue by starandharry** [SysCV/transfiner#18]
When I tried to run demo.py this warning occured, how could I solve it?

Some model parameters or buffers are not found in the checkpoint:
roi_heads.mask_head.deconv_uncertain.{bias, weight}
roi_heads.mask_head.encoder.conv_fuse.{bias, weight}
roi_heads.mask_head.encoder.conv_r1.0.{bias, weight}
roi_heads.mask_head.encoder.conv_r1.2.{bias, weight}
roi_heads.mask_head.encoder.layers.0.linear1.{bias, weight}
roi_heads.mask_head.encoder.layers.0.linear2.{bias, weight}
roi_heads.mask_head.encoder.layers.0.norm1.{bias, weight}
roi_heads.mask_head.encoder.layers.0.norm2.{bias, weight}
roi_heads.mask_head.encoder.layers.0.self_attn.out_proj.{bias, weight}
roi_heads.mask_head.encoder.layers.0.self_attn.{in_proj_bias, in_proj_weight}
roi_heads.mask_head.encoder.layers.1.linear1.{bias, weight}
roi_heads.mask_head.encoder.layers.1.linear2.{bias, weight}
roi_heads.mask_head.encoder.layers.1.norm1.{bias, weight}
roi_heads.mask_head.encoder.layers.1.norm2.{bias, weight}
roi_heads.mask_head.encoder.layers.1.self_attn.out_proj.{bias, weight}
roi_heads.mask_head.encoder.layers.1.self_attn.{in_proj_bias, in_proj_weight}
roi_heads.mask_head.encoder.layers.2.linear1.{bias, weight}
roi_heads.mask_head.encoder.layers.2.linear2.{bias, weight}
roi_heads.mask_head.encoder.layers.2.norm1.{bias, weight}
roi_heads.mask_head.encoder.layers.2.norm2.{bias, weight}
roi_heads.mask_head.encoder.layers.2.self_attn.out_proj.{bias, weight}
roi_heads.mask_head.encoder.layers.2.self_attn.{in_proj_bias, in_proj_weight}
roi_heads.mask_head.mask_fcn_uncertain1.{bias, weight}
roi_heads.mask_head.mask_fcn_uncertain2.{bias, weight}
roi_heads.mask_head.mask_fcn_uncertain3.{bias, weight}
roi_heads.mask_head.mask_fcn_uncertain4.{bias, weight}
roi_heads.mask_head.predictor_semantic_s.{bias, weight}
roi_heads.mask_head.predictor_uncertain.{bias, weight}
roi_heads.mask_pooler.conv_norm_relus_semantic.0.{bias, weight}
roi_heads.mask_pooler.conv_norm_relus_semantic.2.{bias, weight}
roi_heads.mask_pooler.conv_norm_relus_semantic.4.{bias, weight}
roi_heads.mask_pooler.conv_norm_relus_semantic.6.{bias, weight}

**Comment by lkeab** [comment]
which checkpoint are you using? could you share your specific command for running the code?

**Comment by starandharry** [comment]
the command is "python demo.py --input sample_imgs/000000008844.jpg --output results"
 [Checkpointer] Loading from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl ...
and i didnt modify any default settings except path

**Comment by zxf29** [comment]
Hello, I met this problem too, have you solved it?

**Comment by starandharry** [comment]
> Hello, I met this problem too, have you solved it?

I'm sorry because I didn't try after this

**Comment by zxf29** [comment]
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SysCV/transfiner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SysCV/transfiner] Some model parameters or buffers are not found in the checkpoint (Issue #18)





  
Hello, I met this problem too, have you solved it?
  
I'm sorry because I didn't try after this
