### ISSUE TITLE
EasyInstallDeprecationWarning: easy_install command is deprecated.

### ISSUE THREAD

**Issue by Z-star1** [SysCV/transfiner#19]
:~/Downloads/cocoapi-master/PythonAPI$ python setup.py build_ext install
running build_ext
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
running install
/home/zhujie01/miniconda3/envs/transfiner/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/zhujie01/miniconda3/envs/transfiner/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
error: [Errno 13] Permission denied

**Comment by lkeab** [comment]
It seems a problem regarding to cocoapi. You could have a look at this [instruction](https://stackoverflow.com/questions/59620543/setup-py-install-running-egg-info-error-errno-13-permission-denied-regarless).

**Comment by kobecurry30** [comment]
damn
