### ISSUE TITLE
Which detectron2 commit did you refer ？

### ISSUE THREAD

**Issue by ysl2** [SysCV/transfiner#2]
I cannot check out which parts of codes are modified and which parts are copied from detectron2.

**Comment by lkeab** [comment]
Hi, the main modifications are in the [mask_head.py](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/roi_heads/mask_head.py) and [poolers.py](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/poolers.py).
