### ISSUE TITLE
Asking for code component

### ISSUE THREAD

**Issue by trqminh** [SysCV/transfiner#20]
Hi @lkeab,
Thank you for your consideration.

I see that the proposed method is mainly in `mask_head.py`, however, I find the code is hard to keep track. Would you mind showing me where is the code for this component below?

![image](https://user-images.githubusercontent.com/30286786/169103643-337c8cb9-d376-4c88-9b70-045c71921a2a.png)

**Comment by lkeab** [comment]
Hi, thanks for watching our work Transfiner.
The sequence encoder is: [class TransformerEncoder, L928 to L957](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/roi_heads/mask_head.py#L928).
The pixel decoder is [conv_r1, L935](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/roi_heads/mask_head.py#L935).
The incoherent query sequence sent into the transformer for refinement is [here](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/roi_heads/mask_head.py#L495) during training, while [here](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/roi_heads/mask_head.py#L659) during inference.

**Comment by trqminh** [comment]
Thanks, @lkeab for your answer.
Could I ask about the size of the incoherent query sequence according to those pyramid features maps?
Thank you.

![image](https://user-images.githubusercontent.com/30286786/169332532-c54959c1-73c6-4517-8db6-e199976eb242.png)

**Comment by lkeab** [comment]
N x C, N is the number of the detected incoherent query points. The size of N depends on different objects but much smaller than total points in the RoI region.

**Comment by trqminh** [comment]
Thank you @lkeab .

**Comment by trqminh** [comment]
Hi @lkeab ,
So here is what I check the size of the incoherent query points, could you help me elaborate on those numbers.
Thank so much
![image](https://user-images.githubusercontent.com/30286786/169626382-f5345f0c-6d80-4a42-97b9-c8b763eb0f62.png)

**Comment by 128ve900** [comment]
> 
May I ask whether different samples have different values ​​of N? Is the input size of the incoherent query sequence indeterminate?
