### ISSUE TITLE
 no predicted box and category

### ISSUE THREAD

**Issue by Rain-yal** [SysCV/transfiner#21]
Hi, I am a newbie. After running demo.py, there is only a mask in the predicted image result, but there is no predicted box and category? why is that? How can I make them show up?

**Comment by lkeab** [comment]
You can control it [here](https://github.com/SysCV/transfiner/blob/c854ad64088a8b21a3cafcae48411a886416634f/detectron2/utils/visualizer.py#L684) and [here](https://github.com/SysCV/transfiner/blob/c854ad64088a8b21a3cafcae48411a886416634f/detectron2/utils/visualizer.py#L741).

**Comment by Rain-yal** [comment]
Thank you very much! This works.
