### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by PDahal2871** [SysCV/transfiner#23]
After trying to debug for hours, I found that this error is causing because only 1 value is returned instead of 5 values from this code:

File location:
```
detectron2/modeling/roi_heads/mask_head.py
```
In the line 186, if the length of `instances` is 1 and in the line 189, if `if len(instances_per_image) == 0` statement is `True`, then it will skip the whole `for-loop`.

Then, it will reach at line 237, which will become `True` and enters into this block. In line 238, instead of returning 5 loss values, there is only 1 value returned which caused the main error. I replaced the line as :
```
return torch.tensor(0), torch.tensor(0), torch.tensor(0), torch.tensor(0), torch.tensor(0)
```
It temporarily solved the error, but I wanted to know what should be ideal value of losses that should be returned.?
@lkeab

**Comment by lkeab** [comment]
In this case, you can separate the added loss items [here](https://github.com/SysCV/transfiner/blob/main/detectron2/modeling/roi_heads/mask_head.py#L238) with comma. This only happens when there is no GT mask for an input image. If this image is in your training set, it indicates it can be deleted.

**Comment by PDahal2871** [comment]
If I separate it with comma then it will return 4 values instead of 5. And also, since every value is multiplied by 0, would not it be a 0 returned as a loss?

**Comment by lkeab** [comment]
You can simply duplicate one value. It can avoid the error "some variables are in involved in loss computation".
