### ISSUE TITLE
 got fvcore.common.checkpoint WARNING

### ISSUE THREAD

**Issue by wangxueping78** [SysCV/transfiner#24]
Thanks for your great contribution！
Except for changing the dataset, everything else is in accordance with the repo guidance，but I get this warning when training with my own coco format dataset：fvcore.common.checkpoint WARNING: Some model parameters or buffers are not found in the checkpoint:
 [34mbackbone.fpn_lateral2.{bias, weight}[0m
[34mbackbone.fpn_lateral3.{bias, weight}[0m
[34mbackbone.fpn_lateral4.{bias, weight}[0m
[34mbackbone.fpn_lateral5.{bias, weight}[0m
[34mbackbone.fpn_output2.{bias, weight}[0m
[34mbackbone.fpn_output3.{bias, weight}[0m
[34mbackbone.fpn_output4.{bias, weight}[0m
[34mbackbone.fpn_output5.{bias, weight}[0m
[34mproposal_generator.rpn_head.anchor_deltas.{bias, weight}[0m
[34mproposal_generator.rpn_head.conv.{bias, weight}[0m
[34mproposal_generator.rpn_head.objectness_logits.{bias, weight}[0m
[34mroi_heads.box_head.fc1.{bias, weight}[0m
[34mroi_heads.box_head.fc2.{bias, weight}[0m
......
 what caused this？

**Comment by lkeab** [comment]
The initial backbone weight Resnet 50 or 101 does not have these parameters.

**Comment by wangxueping78** [comment]
Oh,how to avoid this problem?
