### ISSUE TITLE
what is the pred_class index refer to?

### ISSUE THREAD

**Issue by anl13** [SysCV/transfiner#27]
Hello, I wonder what is the output `pred_class` refer to? Does it follow COCO classes names just like https://gist.github.com/AruniRC/7b3dadd004da04c80198557db5da4bda?  
When I run on the demo images, I found that the class index for `people` is `0`, the class index for `mouse` is `15`, is that correct?

**Comment by lkeab** [comment]
Hi, you can refer to the category orders [here](https://github.com/SysCV/transfiner/blob/main/detectron2/data/datasets/builtin_meta.py).

**Comment by anl13** [comment]
interesting. It recognize mouse as 'cat', haha.
