### ISSUE TITLE
about the detected incoherent masks module

### ISSUE THREAD

**Issue by DDGRCF** [SysCV/transfiner#3]
Hello! I am interesting in your work. But I have a question about that 
` use a simple fully convolutional network (four 3×3
Convs) followed by a binary classifier to predict the coars-
est incoherence masks. Then, the detected lower-resolution
masks are upsampled and fused with the larger-resolution
feature in neighboring level to guide the finer incoherence
predictions, where only **single 1×1 convolution layer i**s em-
ployed.` 
single 1*1 convolutin layer, I can't find in the code. And can you give a guide, thanks!!!

**Comment by lkeab** [comment]
Hi, thanks for watching. This part is simplified in this current released version with upsampling, as we observe similar visual effects (Up-sampling the lowest-resolution uncertain masks produce a super set). We will further update this after more code organizations.
