### ISSUE TITLE
transfiner to detectron2

### ISSUE THREAD

**Issue by Mrwangxin1998** [SysCV/transfiner#30]
Hi，I want know if I can build the detectron2 environment first ，then I copy transfiner project code to detectron2 project?

**Comment by lkeab** [comment]
Hi, I have not tried this. For current code version, as we made a deep modification to original code in some python files, you need to make sure the modification parts to detectron2 is executed (by overwritting) when placing transfiner in the project folder. My suggestion is to use our code to build detectron2 environment directly.

**Comment by Mrwangxin1998** [comment]
Hi，I tried this way，No errors found so far
