### ISSUE TITLE
Finetuning on Dataset that only contains human

### ISSUE THREAD

**Issue by nixczhou** [SysCV/transfiner#32]
Hi, may I know how to finetune MaskTransfiner in dataset that only contains human as the object?

**Comment by lkeab** [comment]
you can set the class number to 1 and delete the original 80 classes embedding weights. Or you set the class index of the human dataset the same as coco index.

**Comment by nixczhou** [comment]
will there be any step by step method to do this? Or do I just have to provide the human dataset in the coco format?

**Comment by lkeab** [comment]
The quickest way is to make you human dataset in coco format. You can refer to more details [here](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html).
