### ISSUE TITLE
 ‘max_mem’ keeps increasing

### ISSUE THREAD

**Issue by csljtll** [SysCV/transfiner#34]
During the training of my data set, ‘max_mem’ keeps increasing, and finally the video memory is not enough, which causes the training to stop.

**Comment by lkeab** [comment]
what do you mean by 'video memory'? what's the backbone you are using?

**Comment by csljtll** [comment]
CUDA memory.I use resnet50.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SysCV/transfiner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 晚上10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SysCV/transfiner]  ‘max_mem’ keeps increasing (Issue #34)





 
what do you mean by 'video memory'? what's the backbone you are using?

**Comment by lkeab** [comment]
You can refer to the discussion [here](https://github.com/SysCV/transfiner/issues/36).
