### ISSUE TITLE
Could you wirte a document about how to fine-tune your pre-trianed weight plz?

### ISSUE THREAD

**Issue by Metal-joker** [SysCV/transfiner#37]

**Comment by lkeab** [comment]
If you want to do finetuning based on our pretrained model, you can modify the weight location [here](https://github.com/SysCV/transfiner/blob/main/configs/transfiner/mask_rcnn_R_101_FPN_3x.yaml#L3) with corresponding config file.

**Comment by Metal-joker** [comment]
oh thanks, let me try it out

**Comment by Metal-joker** [comment]
@lkeab does normal training need extra models? I ran `bash scripts/train_transfiner_3x_swinb.sh` without any modification, but it still says `AssertionError: Checkpoint swin_base_patch4_window7_224_22k_d2.pth not found!`.
where can I download this model? is there any other model required?

**Comment by Metal-joker** [comment]
ah, nvm. I found this the link in the readme doc [here](https://drive.google.com/file/d/1qvNwe4Ax79OqHQnJp5elFuVYsxUiYviJ/view?usp=sharing) my bad
