### ISSUE TITLE
Strange visualization result.

### ISSUE THREAD

**Issue by Rapisurazurite** [SysCV/transfiner#38]
When I executed the visualization command
 ```python3 demo/demo.py --config-file configs/transfiner/mask_rcnn_R_50_FPN_3x.yaml ----input 'demo/sample_imgs/000000018737.jpg'  --opts MODEL.WEIGHTS ./pretrained_model/output_3x_transfiner_r50.pth```
The result of segmenting the picture 000000018737.jpg in the demo is strange, why is this? 
My pytorch version is 1.10, is it a problem caused by the pytorch version?

000000018737.jpg
![000000018737](https://user-images.githubusercontent.com/43494437/186909267-1b02ecc5-899f-46b8-844b-68841cf07670.jpg)
000000321214.jpg
![000000321214](https://user-images.githubusercontent.com/43494437/186909320-c3b58a42-98c7-4a4f-b502-4c2d99ca3db7.jpg)
000000132408.jpg
![000000132408](https://user-images.githubusercontent.com/43494437/186909446-c8cabc2f-575c-482c-9e0f-6e0f1027ebbf.jpg)

**Comment by lkeab** [comment]
That's due to some incorrect bounding box detection results in small backbone. You can eliminate it by setting higher confidence thresholds or change to lager backbone.
