### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [SysCV/transfiner#4]
Hi, would you be interested in adding transfiner to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by lkeab** [comment]
Thanks AK. I will schedule my time, and work on it in the next weeks. I will contact you if I meet problems during the integration process.

**Comment by lkeab** [comment]
Hi, we have added the Huggingface demo here. Please see [here](https://huggingface.co/spaces/lkeab/transfiner): https://huggingface.co/spaces/lkeab/transfiner

**Comment by AryanKaushal2002** [comment]
> Hi, we have added the Huggingface demo here. Please see [here](https://huggingface.co/spaces/lkeab/transfiner): https://huggingface.co/spaces/lkeab/transfiner

@Ikeab  the model is no longer working. Its showing runtime error. Will it be possible to make it accessible again?
Thanks!
