### ISSUE TITLE
Inference example

### ISSUE THREAD

**Issue by vanga** [SysCV/transfiner#7]
Hi,

I could not find information on how to do inference.
Getting started link here seems to be broken https://github.com/SysCV/transfiner/tree/main/demo

Is there an inference example?

Thanks.

**Comment by lkeab** [comment]
Thanks for the suggestions. We will add some demo inference images soon.

**Comment by lkeab** [comment]
You could first refer to the visualization script [here](https://github.com/SysCV/transfiner#visualization).
