### ISSUE TITLE
Error list image path

### ISSUE THREAD

**Issue by KudoKhang** [SysCV/transfiner#9]
hi,
when i run code your code in Colab have error at line 106 ```demo/demo.py```:
```
106| args.input = glob.glob(os.path.expanduser(args.input[0]))
```
it not return a list of image path. but if change:
```
106| args.input = [args.input[0] + '/' + name for name in os.listdir(args.input[0]) if name.endswith(('png', 'jpg', 'jpeg'))]
```
it work!
And the mask result not good as you said, can you tell me how to get a perfect result as your paper

**Comment by lkeab** [comment]
This is [script](https://github.com/SysCV/transfiner/blob/main/scripts/visual.sh) we recommend for visualization. Current checkpoint is a retrained beta version, we will update the final released checkpoints before CVPR.
